### ISSUE TITLE
App wont open

### ISSUE THREAD

**Issue by bnbagiz** [prashantgupta24/automatic-mouse-mover#18]
im on version 10.12.6
the app wont open, tried via right click and "open" but nothing happens

**Comment by prashantgupta24** [comment]
Hello @bnbagiz, sorry to hear that. Can you provide more information?

1. 10.12.6 is a version of what exactly? 
2. I would advise you to go to the [latest](https://github.com/prashantgupta24/automatic-mouse-mover/releases/tag/v1.0.2) release and try to download the app and open.
3. If that still doesn't work, can you let me know which mac OS you are running?
4. Also a screenshot of what happens when you right click and select `open`? 

All this should hopefully help me help you.

**Comment by bnbagiz** [comment]
Hi,
1. yes that a macOS version.
2. i donwloaded the latest version, tried it with my newer mac (11.1) which works, but on my older machine it does not seem to work. any chance to fix that for older mac versions?
3. yeah literally nothing happens, the message board disappears, after I click on "open" and that's it.

**Comment by prashantgupta24** [comment]
Hmm. I am currently on Mac OS 10.15.7, and it works fine for me. So it looks like it is an issue with 10.12.x and before perhaps.

I will try to see if I can download an earlier version of mac and test it out there.

**Comment by SunboX** [comment]
Same for me now. Wont open. :/ 
<img width="591" alt="Bildschirmfoto 2022-05-19 um 06 56 03" src="https://user-images.githubusercontent.com/83344/169211046-daaed927-2567-4a88-b36d-e9e704f0e3ef.png">

**Comment by MichaelWalker-git** [comment]
Hey @SunboX, there is nothing to open. If the activity monitor says it is running. The gentle mouse movements will be performed.
