### ISSUE TITLE
Error window ad infinitum

### ISSUE THREAD

**Issue by trijste** [prashantgupta24/automatic-mouse-mover#35]
I logged in this morning to find aam had produced three hundred error windows cascading up and down my screen.

Each error said, "unable to move the mouse," with coordinates, a time stamp, and directions to see the readme. 

I have uninstalled it for the time being, but I found this utility useful for a particular problem I was having. Through Setapp, I'm trying Lungo now...

**Comment by prashantgupta24** [comment]
Oof, this is the equivalent of the blue screen, only a lot more unfriendly! 

Lungo sounds interesting! Although with a subscription fee I imagine it has to be!

**Comment by ebeuerle** [comment]
I have this issue as well on my Mac.

**Comment by alican** [comment]
@prashantgupta24 

I have the same Problem and the origin is here:
https://github.com/prashantgupta24/automatic-mouse-mover/blob/master/pkg/mousemover/mouseMover.go#L76

I think the Problem is that the mouse is moved but the underlaying library (robotgo?) didn't get the correct coordinates and returns here a false: https://github.com/prashantgupta24/automatic-mouse-mover/blob/master/pkg/mousemover/mouseMoverUtil.go#L54

Because I get the errors with a unlocked Desktop periodically when I doesnt touch the mouse but the System still doesnt go to standby.

Why do you not using the notify package? https://github.com/prashantgupta24/automatic-mouse-mover/blob/master/pkg/notify/notify.go 
I think showAlert from the robotgo package is not a proper method to show errors like this. Just write it to the logs.

**Comment by prashantgupta24** [comment]
Fix incoming!
